version: "3.7"

services:
#--------------------------------------------
 api:
  build:
   context: ./
   dockerfile: ./srcs/api/Dockerfile
  restart: on-failure
  
  command: bash -c "python manage.py runserver 0.0.0.0:8000"

      
  ports:
   - 8000:8000
      
  env_file:
   - ./srcs/.env
      
  networks:
   - e2e_net
   
  depends_on:
   - db

#--------------------------------------------
 db:
  image: postgres
  restart: on-failure
  
  volumes:
   - e2e-db:/var/lib/postgresql/data
      
  env_file:
   - ./srcs/.env
   
  networks:
   - e2e_net

networks:
 e2e_net:


volumes:
 e2e-db:
