# Generated by Django 4.0.4 on 2022-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_auth',
            field=models.IntegerField(default=0, verbose_name='count checkID requests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='count_checkAddr',
            field=models.IntegerField(default=0, verbose_name='count checkAddr requests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='count_checkId',
            field=models.IntegerField(default=0, verbose_name='count checkID requests'),
        ),
    ]
